### ISSUE TITLE
Wish there was a video I could follow from start to scratch

### ISSUE THREAD

**Issue by redimongo** [slovnicki/bottom_navigation_bloc#1]
First let me say really well done.
As a new flutter coder I am learning by diving deep into examples - and your code is perfect as it is 100% what I have been looking for. saying this, it would be great if there was a blog post or a youtube video that I and others could follow along from start to finish. As I downloaded the git file and added a page (successfully - after a few errors) but now I need to figure out how i can, copy the template into a new flutter app so it has my apps name.

I understand I could just change a few things in Pubspec.yaml and androidManifest.xml (mainly to get it to show my apps name).

Anyway really great starting template - just need a how to document.

**Comment by slovnicki** [comment]
Thank you for your interest in this project. I was planning to write an article on Medium describing the process of developing this. I hope to do it soon and I will let you know in this thread

**Comment by slovnicki** [comment]
I have written an article at Medium and put the link in README
https://medium.com/@lovnicki.sandro/flutter-bottomnavigationbar-with-bloc-pattern-bba6f13d49f3
